### ISSUE TITLE
Does not scale properly on Android pixel with Android 10 OS

### ISSUE THREAD

**Issue by arickatz** [jsuarezruiz/DrinksGalleryApp#1]
When scrolling to the second page, second image remains large and in the edge of the screen

**Comment by jsuarezruiz** [comment]
Could you sync the code and try again?. 
![drinksgalleryapp-droid](https://user-images.githubusercontent.com/6755973/67639192-20a2f980-f8ed-11e9-807b-8d9dc103287e.gif)

**Comment by arickatz** [comment]
I downloaded the updated source from Git,
Yet the problem remains on my Pixel 2.0, the shipping to the right the next image starts at the right edge with an increased size and on each view
In the carousel the initial size and position increase more.
There might be a problem in the behavior of  getting the correct screen size or offset in different Android models.

**Comment by arickatz** [comment]
I also ran it on the Pixel 2 emulator with Oreo and it behaved in the same way as on my physical device.

**Comment by VConhariki** [comment]
That happened to me too, screenshot linked below:

![Screenshot_1607517883](https://user-images.githubusercontent.com/43683627/101632325-80cb0100-3a04-11eb-889f-9082c1e28fed.png)
![Screenshot_1607517886](https://user-images.githubusercontent.com/43683627/101632327-81fc2e00-3a04-11eb-9cdc-f4d8fdde4c9f.png)
![Screenshot_1607517888](https://user-images.githubusercontent.com/43683627/101632328-8294c480-3a04-11eb-9653-458fc5c9a579.png)

Cellphone description: Pixel 2 Pie 9.0
